# Generated by Django 4.0.3 on 2022-03-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
    ]
