# Generated by Django 4.0.3 on 2022-04-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False},
        ),
    ]
