# Generated by Django 4.0.3 on 2022-04-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='待支付', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(default='', max_length=120),
        ),
    ]
